### PR TITLE
Add avro_utils for generating fake Avro test data

### PR DESCRIPTION
**Pull request by jladieu**
One-time setup:

```
python3 -m venv venv
source venv/bin/activate
pip install fastavro faker
```

For usage, run without any args:
```
python avro_utils.py
```

### CODE REVIEW

**Comment by jladieu** [comment]
@calypsomatic I got an opaque error `KeyError: 'name'` when running the script without a fully qualified path which is what prompted me to adjust the instructions to include fully qualified paths.   Is that what you saw?  In either case can you share your output?  Thanks for trying it out.

**Comment by jladieu** [comment]
Oops, sorry!   I accidentally dropped the link to the doc in the PR description, I meant to include: https://docs.google.com/document/d/1aMbgKMfVcgSQR8TbIpJKV2F0el0P7q8wHm7C-JjFSdU/edit#heading=h.sraqa81oze35 which has instructions spelling out to use a qualified path to the files.

I realize now that's not clear in the actual code-based comments.

**Comment by calypsomatic** [comment]
Hmm, strangely with the absolute paths i can successfully create a pfb, but when I try to look at it with pypfb (e.g. `pfb show -i generated_records.avro -n 1`) , I get a key error.  I can LOOK at the data in the avro viewer plugin in Intellij and see that the key it was throwing an error on is there so not sure what the deal is.

**Comment by jladieu** [comment]
Oh interesting!    It wouldn't surprise me if the script is generating file that is considered invalid according to pfb show...I only tested the output by looking at the file in the Avro viewer plugin.

I'll take a look at it through the lens of the pfb cli utility and see if I can make sense of it.

**Comment by jladieu** [comment]
Putting this back in draft after @calypsomatic helped me realize that naively generating Avro doesn't produce anything remotely useful as PFB.

**Pull request closed without merging**
